### ISSUE TITLE
class rentals income account

### ISSUE THREAD

**Issue by jmbarcial** [sdcc-i-coop-portal/zoom109#10]
- member / non-member / organization
> account_code
- (3)441500 Rental Income
- (4)441503 Rental Income SL
- (5)441503010 individual
- (5)441503020 organization
- (4)441506 Rental Income MISC
- (5)441506010 PT Hall
- (5)441506010 Seminar Room
> policy
- advance payment upon opening - profile (osp,ao,apd,cri) / transaction / journal / ledger
- no advance payment upon opening - profile
- no (apm, hap) if members only

**Comment by regiboy** [comment]
[NON] Insertion of term_no, contract_no?

**Comment by regiboy** [comment]
Leaving for discussion tomorrow (October 7, 2017):
Class rentals income (with contract):
- Member / Non-member / Organization
- May SL talaga siya
- On account creation...
	- Ask for term (counted as months)
	- Kelan yung date start? CURRENT_DATE or input?
	- whole payment is user input
	- monthly payment is automatically computed
	- lookup table ng ipapa-rent (not a priority)
	- Initial downpayment can be cash or check
		- Wala kasi akong narinig na case na walang downpayment yung 
		  mag-rerent.
	- CRJ siya kahit mapupunta muna yung binayad sa Accrued Expenses.
		Dr: Cash on hand
			Cr: Accrued Expenses
	- Maraming details sa contract:
		- kung every ilang years mag-eescalate yung monthly
		- saan ibabawas yung ibabayad sa RI; sa SD ba (if may SD acct)?
		- and more (hindi muna priority yun)

Class rentals income payment:
- Payment is normally through MISC module.
	- Choose an RI account holder muna syempre.
- If hindi makakabayad si account holder, pwede niya tayo i-inform na gamitin yung
  downpayment niya (Accrued Expense) para bayaran yung RI due niya for the month.
	- Use NON module
		- Dr: Accrued Expense
			Cr: RI 
- If sa SD manggagaling yung bayad niya,
	- Use NON module
		- Dr: SD
			Cr: RI
- Whenever na hindi nagamit ni account holder yung accrued expenses niya,
  i-didisburse yung hindi nagamit papunta kay holder.
	- Use CDE module
		- Dr: Accrued Expenses
			Cr: Cash on bank (choose a bank)

Class rentals charges (taken from the MOA):
- SUB-LESSOR - SDCC
- SUB-LESSEE - Yung account holder
- In case of default (late nabayaran? according to net), the amount of the 
  rental due therein shall be charged a penalty surcharge of 10% per month 
  until such arrears are updated.
- If a judicial action is instituted by SDCC sa account holder, basis of rental
  will be computed by an additional 25% per annum and shall be cumulative and
  compounded.

Class rentals renewal:
- Depending on the contract, if the rental is extended for another period, it is
  subject to a 5% escalation (depends) upon every renewal of the contract.

Statement of Account: (not priority)
- If yung nabayaran ni RI account holder is less than the computed amount due for
  the month, send a statement of account.

**Comment by regiboy** [comment]
Creation of class rentals income account has been transferred to zoom103.
